language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script: 
  - python updateapi.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: python
  target_branch: gh-pages